# Generated by Django 5.1.2 on 2024-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_reseña', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_producto', models.CharField(max_length=100)),
                ('id_cliente', models.CharField(max_length=100)),
                ('calificacion', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
                ('fecha_reseña', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
