# Generated by Django 5.1.2 on 2024-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='id_reseña',
            new_name='id_paciente',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_reseña',
            field=models.DateTimeField(),
        ),
    ]
